- name: Configure WP Server
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Create security group for HTTP
      amazon.aws.ec2_security_group:
        name: "http-sg"
        description: "Allow HTTP inbound traffic"
        region: "eu-central-1"
        rules:
          - proto: tcp
            ports:
              - 80
            cidr_ip: "0.0.0.0/0"
        state: present

    - name: Check Install apache & php
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes

      loop:
        - apache2
        - php
        - php-mysql

    - name: Run apache2
      systemd:
        name: apache2
        state: started
        enabled: yes
