---
- name: Установка WordPress
  hosts: all
  become: yes
  tasks:
    - name: Установка Apache, MySQL и PHP
      yum:
        name:
          - httpd
          - mysql-server
          - php
          - php-mysqlnd
        state: present

    - name: Запуск Apache и MySQL
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - httpd
        - mysqld

    - name: Скачивание WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Распаковка WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        copy: no

    - name: Установка прав на директорию WordPress
      file:
        path: /var/www/html/wordpress
        owner: apache
        group: apache
        mode: 0755
        recurse: yes
