---
- name: Установка пакетов и настройка WordPress
  hosts: all
  become: yes
  tasks:
    - name: Убедиться, что Python 3 установлен
      package:
        name: python3
        state: present

    - name: Установка Apache, MySQL и PHP
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
        state: present
        update_cache: yes

    - name: Перезапуск Apache
      service:
        name: apache2
        state: restarted

    - name: Запуск Apache и MySQL
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - apache2
        - mysql

    - name: Скачивание WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Распаковка WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Проверка наличия папки WordPress
      stat:
        path: /var/www/html/wordpress
      register: wordpress_folder

    - name: Перемещение содержимого WordPress в корень веб-сервера
      shell: |
        if [ -d /var/www/html/wordpress ]; then
          mv /var/www/html/wordpress/* /var/www/html/
        fi
      when: wordpress_folder.stat.exists and wordpress_folder.stat.isdir

    - name: Удаление лишней папки WordPress
      file:
        path: /var/www/html/wordpress
        state: absent

    - name: Установка прав на директорию WordPress
      file:
        path: /var/www/html/
        owner: www-data
        group: www-data
        mode: 0755
        recurse: yes
