name: Deploy and Test Terraform!

on:
  push:
    branches:
      - terra

jobs:
  terraform:
    name: Deploy AMI with Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Setup AWS Credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
        aws configure set region eu-central-1

    - name: Terraform Init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      run: |
        cd terraform
        terraform init

    - name: Terraform Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      run: |
        cd terraform
        terraform apply -var "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY }}" -var "aws_secret_access_key=${{ secrets.AWS_SECRET_KEY }}" -auto-approve
        
        IP_OUTPUT=$(terraform output -raw instance_ip)
        echo "Terraform output: $IP_OUTPUT"
      
        INSTANCE_IP=$(terraform output -raw instance_ip | tr -d '\n' | sed 's/[^0-9.]//g')
        echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV\

    - name: Test HTTP Server
      run: |
        echo "Testing with IP: $INSTANCE_IP"
        chmod +x ./scripts/test.sh
        ./scripts/test.sh $INSTANCE_IP

    - name: Notify Telegram
      if: always()
      env:
        TELEGRAM_TOKEN: ${{ secrets.TG_TOKEN }}
        CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      run: |
        STATUS="FAILED"
        if [ "${{ job.status }}" == "success" ]; then
          STATUS="SUCCESSFUL"
        fi
        curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
          -d chat_id="$CHAT_ID" \
          -d text="Pipeline $STATUS: Deploy and test completed with result ${{ job.status }}."
