name: Deploy and Test Terraform!

on:
  push:
    branches:
      - terra

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set TF_LOG to ERROR (disable debug output)
        run: |
          echo "TF_LOG=ERROR" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Initialize Terraform
        id: init_terra
        working-directory: terraform/
        run: terraform init

      - name: Apply Terraform
        working-directory: terraform/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        id: apply_terra
        run: |
          terraform apply -var "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY }}" -var "aws_secret_access_key=${{ secrets.AWS_SECRET_KEY }}" -auto-approve

      - name: Notify Telegram
        if: always()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TG_TOKEN }}
          CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          STATUS="❌ FAILED ❌"
          INIT_STATUS="❌ FAILED ❌"
          APPLY_STATUS="❌ FAILED ❌"
          TASK_STATUS="❌ FAILED ❌"
          if [ "${{ job.status }}" == "success" ]; then
            STATUS="SUCCESSFUL"
          fi          
          if [ "${{ steps.init_terra.outcome }}" == "success" ]; then
            INIT_STATUS="OK ✅"
          fi         
          if [ "${{ steps.apply_terra.outcome }}" == "success" ]; then
            APPLY_STATUS="OK ✅"
          fi     
          if [ "${{ job.status }}" == "success" ]; then
            TASK_STATUS="Done ✅"
          fi      
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
            -d chat_id="$CHAT_ID" \
            -d text="Pipeline $STATUS:

            Init Terra: $INIT_STATUS
            Apply Terra: $APPLY_STATUS
            Build status: $TASK_STATUS"