name: Deploy and Test Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy AMI with Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      id: apply
      run: |
        terraform apply -auto-approve
        echo "INSTANCE_IP=$(terraform output -raw instance_ip)" >> $GITHUB_ENV

    - name: Test HTTP Server
      run: ./test_http_server.sh $INSTANCE_IP

    - name: Notify Telegram
      if: always()
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        STATUS="FAILED"
        if [ "${{ job.status }}" == "success" ]; then
          STATUS="SUCCESSFUL"
        fi
        curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
          -d chat_id="$CHAT_ID" \
          -d text="Pipeline $STATUS: Deploy and test completed with result ${{ job.status }}."
