name: CI-CD RUN AMI WITH TG

on:
  push:
    branches:
      - terra

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Устанавливаем Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      # 3. Инициализируем Terraform
      - name: Initialize Terraform
        working-directory: terraform/
        run: terraform init

      # 4. Применяем Terraform
      - name: Apply Terraform Configuration
        working-directory: terraform/
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # 5. Получаем IP-адрес созданного экземпляра
      - name: Extract Public IP
        id: get_ip
        working-directory: terraform/
        run: echo "IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV

      # 6. Проверяем доступность HTTP-сервера
      - name: Test HTTP Server
        run: curl -f http://$IP || exit 1

      # 7. Отправляем уведомление в Telegram
      - name: Send Telegram Notification
        env:
          TELEGRAM_TOKEN: ${{ secrets.TG_TOKEN }}
          CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          IP: ${{ env.IP }}
        run: |
          curl -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage \
          -d chat_id=$CHAT_ID \
          -d text="Server is up and running at http://$IP"
